.TH OZWCP 1 2016-12-24
.SH NAME
ozwcp \- OpenZWave Control Panel
.SH SYNOPSIS
.B ozwcp
.RB [ \-d ]
.RB [ \-p
.IR port ]
.SH DESCRIPTION
OpenZWave Control Panel (\fBozwcp\fP) permits users to query, manage, and
monitor Z-Wave nodes and networks. It provides a web-based user interface.
Some example uses include adding/removing nodes, testing commands,
and viewing/changing node configuration parameters.
.PP
Once started, use a web browser to connect to the host:port that ozwcp
is listening on. By default this is <\fI\%http://localhost:8090/\fP>.
Enter the device path, for example \fI\%/dev/ttyACM0\fP,
and press "Initialize". Note that many Z-Wave USB sticks act as serial
devices, and if so, the USB box should not be checked.
.PP
\fBozwcp\fP must be able to exclusively read/write to the controller.
Typically this means running under a user that is a member of
the device group, for example dialout for serial ports,
or changing the permissions of the device file.
Running as root should also work but is not recommended.
Stop other programs that may be using the device before initializing.
.SH OPTIONS
.TP
.B \-d
Enable debugging.
.TP
.BI \-p\  port
Listen on the specified
.I port
instead of 8090.
.SH FILES
.TP
.I /etc/openzwave
OpenZWave configuration files.
.TP
.I /usr/share/openzwave-controlpanel
Static files for the web server.
.TP
.I ozwcache_*.xml
Cache of the current network configuration, formerly
\fI\%zwcfg_*.xml\fP.
.TP
.I OZW_Log.txt
OpenZWave log file, useful for debugging.
.SH AUTHORS
ozwcp was written by Greg Satz <satz@iranger.com> and maintained by
Justin Hammond <justin@dynam.ac> and other contributors.
.PP
This manual page was written by Dara Adib <daradib@ocf.berkeley.edu>
for the Debian project (but may be used by others).
.SH SEE ALSO
.I /usr/share/doc/openzwave-controlpanel/README
